#
# Local site settings
remote_theme: wet-boew/gcweb-jekyll
title: "GCWeb, the Canada.ca official theme" # Site name or title
global:
  lang: en
 
 
  applicationName:
    en: "My application"
    fr: "Mon application"
  applicationURL:
    en: "#"
    fr: "#"

#
# Page front matter defaults
defaults:
  - scope:
      path: "" # Ensure it's applied to all pages
    values:
      layout: default

#
# Collections
collections:
  wetboew-demos:
    output: true

#
# Jekyll settings
timezone: America/Toronto # Timezone for blog posts and alike
sass:
  sass_dir: "sites"


#
# Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE*
- SECURITY.md
- Gruntfile.coffee
- CNAME
- "*.tmp"
- Gemfile
- Gemfile.lock
- gcweb-jekyll.gemspec
- .jekyll-cache
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ~sites/
